# GENERATED by test/gen_constants.py from constants.yaml -- DO NOT EDIT BY HAND.
# To change a value, edit constants.yaml and run
#   python3 test/gen_constants.py --write
"""Audio HAT (WM8960) constants. Generated from constants.yaml, do not edit by hand."""

# --- board ---
BOARD_NAME = 'Audio HAT (WM8960)'  # (design_target)
BOARD_REV = 'R1.1'  # (copper) as printed on F.SilkS, 'WEIRD AUDIO HAT R1.1'

# --- codec ---
I2C_ADDR = 0x1a  # (netlist) WM8960 on i2c-1
# (design_target) the name the driver enumerates as in `aplay -l`
ALSA_CARD_NAME = 'wm8960soundcard'

# --- clock ---
# (design_target) Hz SYSCLK for the 44.1 kHz family, no PLL. minimal_clk generates it on GPCLK0;
# the board has no oscillator.
MCLK_HZ = 11289600
MCLK_GPIO_BCM = 4  # (netlist) J3 pin 7 = BCM4 = GPCLK0 -> R26 -> U1 pin 11 (MCLK)
# (design_target) Not the Pi 5: minimal_clk writes BCM283x clock registers that the RP1 does not
# have, and there is no onboard oscillator.
PI_MODELOS_SOPORTADOS = ['Pi 1', 'Pi 2', 'Pi 3', 'Pi 4', 'Zero 2 W']

# --- capture ---
# (design_target) the format for arecord / aplay. Not S24_3LE, not `-f cd`.
SAMPLE_FORMAT = 'S32_LE'
# (derived) Hz The 44.1 kHz family that MCLK_HZ allows. 48 kHz needs a 12.288 MHz clock and a
# device-tree change.
SAMPLE_RATE_HZ = 44100
CHANNELS = 2  # (netlist)

# --- jacks ---
# (netlist) Inputs are single-ended (LINPUT1/2 and RINPUT1/2 unconnected), so differential mode
# is not possible. J1 is the only one with MICBIAS, switched by SW1.
JACKS = (
    {'J5': {'dir': 'in', 'channel': 'L', 'pin': 'LINPUT3'},
     'J1': {'dir': 'in', 'channel': 'R', 'pin': 'RINPUT3'},
     'J4': {'dir': 'out', 'channel': 'LR', 'pin': 'HP_L/HP_R'},
     'J2': {'dir': 'out', 'channel': 'mono', 'pin': 'OUT3'}}
)

# --- loopback ---
# (design_target) audio_loopback.py prints it; stack_test.py looks for it
LOOPBACK_NO_SIGNAL = 'NO SIGNAL'
# (design_target) audio_loopback.py prints it; stack_test.py looks for it
LOOPBACK_CROSSED = 'CROSSED'
# (design_target) audio_loopback.py prints '<this> N dB'; stack_test.py reads N from it
LOOPBACK_SEPARATION = 'separation'
