#!/usr/bin/env python3
"""Generates the board's constants module in test/ from constants.yaml. Runs on the laptop.

constants.yaml is the only source; the module exists because a fresh Pi has no PyYAML.

  python3 gen_constants.py --write    regenerate the module
  python3 gen_constants.py --check    fail if the module is out of date

Identical in the three board repos.
"""

import argparse
import os
import pprint
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
YAML = os.path.join(os.path.dirname(HERE), "constants.yaml")
def _output_path():
    """Named per board, so another board's module fails to import instead of loading."""
    import yaml
    with open(YAML) as f:
        name = yaml.safe_load(f).get("_module_name")
    if not name:
        sys.exit("constants.yaml does not declare _module_name")
    return os.path.join(HERE, name + ".py")

BANNER = "# GENERATED by test/gen_constants.py from constants.yaml -- DO NOT EDIT BY HAND."


WIDTH = 96


def comment(text):
    return textwrap.wrap(text, width=WIDTH, initial_indent="# ", subsequent_indent="# ",
                         break_long_words=False, break_on_hyphens=False)


def assignment(name, value, fmt=None):
    """`NAME = value`, split with pprint if it does not fit on one line."""
    if fmt == "hex" and isinstance(value, int):
        return ["%s = %#x" % (name, value)]
    one = "%s = %r" % (name, value)
    if len(one) <= WIDTH:
        return [one]
    body = pprint.pformat(value, width=WIDTH - 4, sort_dicts=False)
    return ["%s = (" % name] + ["    " + ln for ln in body.splitlines()] + [")"]


def load():
    try:
        import yaml
    except ImportError:
        sys.exit("PyYAML is missing: pip install pyyaml  (only needed to regenerate)")
    with open(YAML) as f:
        return yaml.safe_load(f)


def render(doc):
    lines = [
        BANNER,
        "# To change a value, edit constants.yaml and run",
        "#   python3 test/gen_constants.py --write",
        '"""%s"""' % doc.get("_module_doc", "Board constants."),
        "",
    ]
    for group, entries in doc.items():
        if group.startswith("_"):
            continue
        lines.append("# --- %s ---" % group)
        for name, e in entries.items():
            note = " ".join(e.get("note", "").split())
            unit = (" " + e["unit"]) if e.get("unit") else ""
            head = "(%s)%s%s" % (e.get("source", "?"), unit, (" " + note) if note else "")
            body = assignment(name, e["value"], e.get("format"))
            trailing = "%s  # %s" % (body[0], head)
            if len(body) == 1 and len(trailing) <= WIDTH:
                lines.append(trailing)
            else:
                lines.extend(comment(head))   # long note or split value: comment goes above
                lines.extend(body)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--write", action="store_true", help="regenerate the constants module")
    p.add_argument("--check", action="store_true", help="fail if out of date")
    a = p.parse_args()
    if not (a.write or a.check):
        p.error("choose --write or --check")

    out = _output_path()
    want = render(load())
    have = open(out).read() if os.path.exists(out) else None

    if a.check:
        if have != want:
            print(os.path.basename(out) + " is out of date with constants.yaml.",
                  file=sys.stderr)
            print("Regenerate with: python3 test/gen_constants.py --write", file=sys.stderr)
            return 1
        print(os.path.basename(out) + " in sync with constants.yaml")
        return 0

    if have == want:
        print(os.path.basename(out) + " already in sync")
        return 0
    with open(out, "w") as f:
        f.write(want)
    print("%s regenerated (%d lines)" % (os.path.basename(out), want.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
